### ISSUE TITLE
One day races ranking scraping

### ISSUE THREAD

**Issue by pierrotvz** [themm1/procyclingstats#12]
Hello,

Your work is fantastic.
Unfortunately, the one day race ranking is identified as a race ranking and the parsing doesn't work.
Can you adapt the code for the one day racing?

I have the issue with the default:
https://www.procyclingstats.com/rankings/me/uci-one-day-races

or with a filtered request :
https://www.procyclingstats.com/rankings.php?date=2022-12-31&nation=&age=&zage=&page=smallerorequal&team=&offset=0&filter=Filter&p=me&s=one-day-races

here is the error:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/pavz/Library/Python/3.9/lib/python/site-packages/procyclingstats/scraper.py", line 112, in parse
    parsed_data[method_name] = method()
  File "/Users/pavz/Library/Python/3.9/lib/python/site-packages/procyclingstats/ranking_scraper.py", line 212, in races_ranking
    table_parser.parse(fields)
  File "/Users/pavz/Library/Python/3.9/lib/python/site-packages/procyclingstats/table_parser.py", line 102, in parse
    raise UnexpectedParsingError(message)
procyclingstats.errors.UnexpectedParsingError: Field 'stage_name' wasn't parsed correctly

Thank you

**Comment by themm1** [comment]
Thank you for reporting. It's fixed now, however it's not yet on PyPI so you have to install latest version manually from GitHub as shown in README.md. I will update new version on PyPI in a few weeks, after I fix/update some more things.
