### ISSUE TITLE
Problem scraping when trying to run the method team.riders()

### ISSUE THREAD

**Issue by cecper** [themm1/procyclingstats#16]
when running version procyclingstats==0.1.7 this code:
```
from procyclingstats import Team


team = Team("team/bora-hansgrohe-2022")
print(team.riders())
```

results in this error:
```
Traceback (most recent call last):
  File "C:\Users\user\Documenten\test.py", line 12, in <module>
    print(team.riders())
  File "C:\Users\user\anaconda3\lib\site-packages\procyclingstats\team_scraper.py", line 183, in riders
    table_parser = TableParser(career_points_table_html)
  File "C:\Users\user\anaconda3\lib\site-packages\procyclingstats\table_parser.py", line 31, in __init__
    table_body = html_table.css_first("tbody")
AttributeError: 'NoneType' object has no attribute 'css_first'
```

**Comment by themm1** [comment]
Thanks for reporting an issue. I will take a look at it in a few days.

**Comment by JannesVliegenUCLL** [comment]
any update?

**Comment by themm1** [comment]
Sorry it's kinda late, but it should be fixed now. It's not on PyPI yet so you have to download repo from GitHub manually.
